enableFeaturePreview("VERSION_CATALOGS")
rootProject.name = "Personal Organiser"
rootProject.buildFileName = "build.gradle.kts"
include(":arch")
include(":common")
include(":repository")
include(":app")
include(":app:views:verticalweekcalendar")
include(":app:views:SingleRowCalendar")
include(":app:screens:calendar")
include(":app:screens:empty")
include(":app:ui")
include(":dal")
include(":app:main")
include(":app:tech")
include(":app:tech:sounds")
include(":app:tech:files")
